### ISSUE TITLE
build an RE2 mirror for amd64 and arm64

### ISSUE THREAD

**Issue by viceice** [containerbase/base#1183]
This will speedup renovate installs a lot

**TODO**
- [ ] create new repo
- [ ] build artifacts on the new repo
- [ ] update renovate install to pass mirror options

**Links**
- https://github.com/uhop/node-re2/issues/164#issuecomment-1632948451

**Comment by viceice** [comment]
- https://github.com/containerbase/node-re2-prebuild
