### ISSUE TITLE
Support Ubuntu 22.04 LTS (jammy)

### ISSUE THREAD

**Issue by viceice** [containerbase/base#361]
Should be released this week.
For now we will add support, but stay on 20.04 on official images.

**validated**
- `php >=8.1`
- `powershell >=7.2`
- `python >=3.9`
- `ruby >=3.1`
- `dotnet >=6.0`
- check [`test/Dockerfile.jammy`](https://github.com/containerbase/buildpack/blob/main/test/Dockerfile.jammy) for more tools

**known issues**
- [ ] errors because of openssl changes, so a lot tools are not yet compatible
- [x] #405 
- [x] #406, #409
- [x] `powershell` (same as dotnet, missing libicu), #409
- [x] `python` (missing prebuild binaries), #410
- [x] `swift` https://github.com/apple/swift/issues/58784  (no jammy binaries yet)
- [x] containerbase/erlang-prebuild#10
- [x] #415

**Comment by viceice** [comment]
Closing, as most tools are now working as expected
