### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by jalaziz** [containerbase/base#711]
All `containerbase` images are only built for amd64, it would be great if they were also build for arm64. This would allow dev containers based on `containerbase` (e.g. renovate) to run faster and more efficiently on ARM-based machines like the newer M1 and M2 Apple Macbooks.

**Tasks**
- [x] `dart` #772
- [x] `erlang` #719
- [x] `flutter` #807 
- [x] `java` #500
- [x] `ruby` containerbase/ruby-prebuild#7
- [x] `php` containerbase/php-prebuild#17 #814
- [x] `python` containerbase/python-prebuild#2
- [x] `swift` #805
- [ ] publish multiarch image (amd64 and arm64)
- [ ] renovatebot/renovate#9229

**Comment by rarkins** [comment]
@viceice let's at least document all the parts which would be required for this to happen. e.g. each of the tools we install supports ARM, etc.

**Comment by viceice** [comment]
ok

**Comment by viceice** [comment]
I'll try to support arm as most as possible, but we won't publish arm images, because building them on Linux is very slow.

**Comment by jalaziz** [comment]
> I'll try to support arm as most as possible, but we won't publish arm images, because building them on Linux is very slow.

Do you mean on x64 through emulation? I'm confused as to what Linux has to do with build speeds?

I can understand not wanting to deal with building multi-platform images on x64, but that emulation cost is paid once compared to the time cost paid by everyone who runs the current x64 images emulated on ARM CPUs.

In any case, even having a way to build it all locally would be great.

**Comment by viceice** [comment]
see linked PR, added basic arm support. will do some remaining work the next days.

**Comment by viceice** [comment]
Next step is to publish the base image as multiarch 🎉
